
[general]
	#Allow player that have the wireless technology to access their account without an ATM nearby.
	canAccessCardWithoutWT = true
	#Allow the mod to replace the furnace recipe for the gold ore and give instead the EconomyInc's nugget.
	goldNuggetRecipe = true
	#Allow or not the bank to generate in villages, by default it generates turn it to false to disable its generation.
	doesBankGenerateInVillages = true
	#Define the block use to create the edges of the plot.
	plotBorderBlock = "minecraft:smooth_stone_slab"
	#It will multiply the weight of the nugget with this number to create a funds to add to the credit card.
	#Range: 1 ~ 9999
	multiplierGoldNuggetWeight = 2

