
[dimension]
	#When false, beds used in the Tent Dimension will explode
	"Allow Sleep in Tent" = true
	#When true, weather (ie, rain) is enabled in the tent dimension
	"Enable Weather" = true
	#When true, sleeping in a tent will set your Overworld spawn to the tent's outside location
	"Allow Spawnpoint Logic" = true
	#When true, only creative-mode players can teleport within the Tent Dimension
	"Restrict Teleporting" = true
	#When true, players in a tent can only sleep through the night if overworld players are asleep too
	"Tent Sleeping Strict" = true
	#Dimensions in which tents cannot be used (name or ID)
	"Dimension Blacklist" = ["nomadictents:tent", "-1"]
	#The dimension in which players will respawn from the tent dimension as needed
	"Home Dimension" = "minecraft:overworld"
	#When true, players who die in Tent Dimension will be sent to overworld IF they have no bed
	#(Disable if buggy)
	"Allow Respawn Logic" = true

[permissions]
	#When true, non-player entities can enter the tent by walking through the door
	"Allow Entity Walk-In" = true
	#When true, only the player who placed the tent can pick it up
	"Owner-Only Pickup" = false
	#When true, players can enter the tent by walking through the door
	"Allow Player Walk-In" = true
	#When true, only the player who placed the tent can enter it
	"Owner-Only Entrance" = false
	#When true, only Creative mode players can duplicate a tent item
	#(Note: this is done by clicking a tent door with any item that has NBT tag 'TentCopyTool' set to true)
	"Copy is Creative-Only" = true
	#When true, only Creative-mode players can use the Super Tent Mallet
	"Super Mallet Creative Only" = false
	#When true, players can only enter tents when there are no nearby monsters
	"Prevent Entering when Fighting" = false

[tents]
	#Whether the Yurt can be built and used
	"Enable Yurt" = true
	#Limit the size upgrades an Indlu can recieve. 1=SMALL, 6=MEGA
	#Range: 1 ~ 6
	"Max Tiers: Indlu" = 6
	#Limit the depth of a Medium Tent. 1=No Upgrades, 6=Full Upgrades
	#Range: 1 ~ 6
	"Max Depth: Medium" = 2
	#Enables pre-built features in new tents (torches, campfires, etc)
	"Enable Bedouin Features" = true
	#Whether the Tepee can be built and used
	"Enable Tepee" = true
	#Limit the size upgrades a Shamiyana can recieve. 1=SMALL, 6=MEGA
	#Range: 1 ~ 6
	"Max Tiers: Shamiyana" = 6
	#Limit the depth of a Large Tent. 1=No Upgrades, 6=Full Upgrades
	#Range: 1 ~ 6
	"Max Depth: Large" = 3
	#Enables pre-built features in new tents (torches, campfires, etc)
	"Enable Yurt Features" = true
	#Enables pre-built features in new tents (torches, campfires, etc)
	"Enable Shamiyana Features" = true
	#Whether the Shamiyana can be built and used
	"Enable Shamiyana" = true
	#Limit the depth of a Small Tent. 1=No Upgrades, 6=Full Upgrades
	#Range: 1 ~ 6
	"Max Depth: Small" = 1
	#Enables pre-built features in new tents (torches, campfires, etc)
	"Enable Indlu Features" = true
	#Limit the size upgrades a Yurt can recieve. 1=SMALL, 6=MEGA
	#Range: 1 ~ 6
	"Max Tiers: Yurt" = 6
	#Enables pre-built features in new tents (torches, campfires, etc)
	"Enable Tepee Features" = true
	#Whether the Bedouin can be built and used
	"Enable Bedouin" = true
	#Limit the depth of a Huge Tent. 1=No Upgrades, 6=Full Upgrades
	#Range: 1 ~ 6
	"Max Depth: Huge" = 4
	#Limit the depth of a Giant Tent. 1=No Upgrades, 6=Full Upgrades
	#Range: 1 ~ 6
	"Max Depth: Giant" = 5
	#Limit the size upgrades a Bedouin can recieve. 1=SMALL, 6=MEGA
	#Range: 1 ~ 6
	"Max Tiers: Bedouin" = 6
	#Limit the size upgrades a Tepee can recieve. 1=SMALL, 6=MEGA
	#Range: 1 ~ 6
	"Max Tiers: Tepee" = 6
	#Limit the depth of a Mega Tent. 1=No Upgrades, 6=Full Upgrades
	#Range: 1 ~ 6
	"Max Depth: Mega" = 6
	#Whether the Indlu can be built and used
	"Enable Indlu" = true

[other]
	#When true, tents will be the same size on the outside and inside
	"Use Actual Size" = false
	#Specify the block used for the harvestable layer of all tent floors
	#Format: [mod]:[name] ~ Example: minecraft:sand
	"Tent Floor" = "minecraft:dirt"
	#When true, the tent item will not be destroyed if it is burned
	"Is Tent Fireproof" = false
	#Percentage chance that a plain tepee block will randomly have a design
	#Range: 0 ~ 100
	"Tepee Design Chance" = 35

