
["The Bumblezone Dimension Options"]
	# 
	#-----------------------------------------------------
	#
	# If a resource location of a block is specified here,
	#  then teleporting to Bumblezone will need that block under
	# the Bee Nest/Beehive you threw the Enderpearl at.
	# 
	# Example: minecraft:emerald_block will require you to place an
	# Emerald Block under the Bee Nest/Beehive and then throw an
	# Enderpearl at it to teleport to Bumblezone dimension.
	# 
	# By default, no resource location is specified so any
	# block can be under the Bee Nest/Beehive to teleport to dimension.
	#
	requiredBlockUnderHive = ""
	# 
	#-----------------------------------------------------
	#
	# Determines how the coordinates gets translated when entering 
	# and leaving the Bumblezone. The default ratio is 10 which means
	# for every block you traverse in the dimension, it is equal to
	# traveling 10 blocks in the Overworld. For comparison, the Nether
	# has a 8 to 1 ratio with the Overworld. 
	# 
	# The scaling of coordinates will take into account other dimension's
	# coordinate ratios so it'll work for any dimension correctly.
	# 
	# Note: Changing this in an already made world will change where Bee Nests will
	# take you in the dimension and exiting will place you in a different spot too.
	#
	#Range: 1 ~ 1000
	movementFactor = 10
	# 
	#-----------------------------------------------------
	#
	# If requiredBlockUnderHive has a block specified and this config
	#  is set to true, then player will get a warning if they throw 
	# an Enderpearl at a Bee Nest/Beehive but the block under it is 
	# not the correct required block. It will also tell the player what 
	# block is needed under the Bee Nest/Beehive to teleport to the dimension.
	#
	warnPlayersOfWrongBlockUnderHive = true
	# 
	#-----------------------------------------------------
	#
	# Makes leaving The Bumblezone dimension always places you back
	#  at the Overworld regardless of which dimension you originally 
	# came from. Use this option if this dimension becomes locked in  
	# with another dimension so you are stuck teleporting between the 
	# two and cannot get back to the Overworld.
	#
	forceExitToOverworld = false
	# 
	#-----------------------------------------------------
	#
	# Should teleporting to and from The Bumblezone work 
	# with modded Bee Nests and modded Beehives as well. 
	#
	allowTeleportationWithModdedBeehives = true
	# 
	#-----------------------------------------------------
	#
	# Determines if the day/night cycle active in the Bumblezone dimension.
	#  The cycle will be visible by the change in color of the fog. 
	# If kept on, the day/night cycle will match the Overworld's 
	# cycle even when players sleep to skip night in the Overworld.
	# 
	# If this setting is set to false, the cycle 
	# will be stuck at "noon" for the dimension.
	#
	dayNightCycle = true
	# 
	#-----------------------------------------------------
	#
	# How bright the fog is in the Bumblezone dimension. 
	# This will always affect the fog whether you have the 
	# day/night cycle on or off.
	# 
	# The brightness is represented as a percentage so if the 
	# cycle is off, 0 will be pitch black, 50 will be half as 
	# bright, 100 will be normal orange brightness, and 
	# 100000 will be white. When the cycle is on, 0 will be 
	# but will not be completely black during daytime.
	#
	#Range: 0.0 ~ 100000.0
	fogBrightnessPercentage = 100.0

["Wrath of the Hive Options"]

	["Wrath of the Hive Options"."Bees Effects Options"]
		# 
		#-----------------------------------------------------
		#
		# How much extra health bees get that always instantly regenerates.
		# This means you need to deal more damage than the extra health gives
		# order to actually damage the bee's real health bar.
		# 
		# For example, Absorpton 1 here makes bees get 4 extra padding of hearts.
		# Your attacks need to deal 4 1/2 or more damage to actuall be able to
		# kill the bee. This means using Bane of Arthropod 5 is needed to kill bees
		# if you set the absorption to a higher value like 2 or 3.
		# If you set this to like 5 or something, bees may be invicible! Game over.
		#
		#Range: > 1
		absorptionBoostLevel = 1
		# 
		#-----------------------------------------------------
		#
		# How fast bees move along the ground (Not while flying).
		# You will see this a lot when bees are about to attack
		# you, they tend to touch the floor and the speed boost
		# makes them dash forward at you. Set this to higher for
		# faster dash attacks from bees.
		#
		#Range: > 1
		speedBoostLevel = 1
		# 
		#-----------------------------------------------------
		#
		# How strong the bees attacks become. 
		# (5 or higher will instant kill you without armor).
		#
		#Range: > 1
		strengthBoostLevel = 3

	["Wrath of the Hive Options"."Bees Aggression Options"]
		# 
		#-----------------------------------------------------
		#
		# How far away the bee can be to become angry and hunt you down if
		#  you take their honey from the Bumblezone dimension.
		# 
		# Will also affect the bee's aggression range toward bears in the dimension.
		#
		#Range: 1 ~ 200
		aggressionTriggerRadius = 64
		# 
		#-----------------------------------------------------
		#
		# How long bees will keep their effects for (speed, absorption, strength).
		# Note: This is in ticks. 20 ticks = 1 second.
		#
		#Range: > 1
		howLongWrathOfTheHiveLasts = 350
		# 
		#-----------------------------------------------------
		#
		# Show the orangish particles when you get Wrath of the Hive
		# after you angered the bees in the Bumblezone dimension.
		#
		showWrathOfTheHiveParticles = true
		# 
		#-----------------------------------------------------
		#
		# Determines if Wrath of the Hive can be applied to players outside
		# the Bumblezone dimension when they pick up Honey blocks, take honey
		# from Filled Porous Honey blocks, or drink Honey Bottles.
		#
		allowWrathOfTheHiveOutsideBumblezone = false
		# 
		#-----------------------------------------------------
		#
		# Turn off or on the ability to get Wrath of the Hive effect.
		# 
		# The effect gets applied when you pick up Honey blocks, take
		# honey from Filled Porous Honeycomb Blocks, or drink a
		# Honey Bottle inside the Bumblezone dimension.
		# Basically, bees become REALLY angry.
		# 
		# In addition, the bees can see you through walls and will have 
		# speed, absorption, and strength effects applied to them.
		# 
		# Will also affect the bee's aggression toward bears in the dimension.
		# Note: Peaceful mode will always override the bee aggressive setting.
		#
		aggressiveBees = true

["Mod Compatibility Options"]

	["Mod Compatibility Options"."Beesourceful Options"]
		# 
		#-----------------------------------------------------
		#
		# Spawn Beesourceful's ore and ender bees in The Bumblezone alongside
		# regular bees at a 1/15th chance when spawning regular bees.
		#
		spawnBeesourcefulBeesMob = true
		# 
		#-----------------------------------------------------
		#
		# Spawn Beesourceful's various honeycomb variants in The Bumblezone
		# at all kinds of heights and height bands. Start exploring to find 
		# where they spawn! Especially waaaay above for the Ender Honeycomb! 
		# 
		# NOTE: Will require a restart of the world to take effect. 
		#
		spawnBesourcefulHoneycombVariants = true

	["Mod Compatibility Options"."Buzzier Bees Options"]
		# 
		#-----------------------------------------------------
		#
		# Place Buzzier Bees's Crystallized Honey Blocks on the /r/n surface of land around sea level and above.
		#
		crystallizedHoneyWorldgen = true
		# 
		#-----------------------------------------------------
		#
		# Place Hive Planks blocks at the top and bottom of the dimension 
		# so it is like the dimension is actually in a Bee Nest block.
		#
		hivePlanksWorldgen = true
		# 
		#-----------------------------------------------------
		#
		# Spawn Buzzier Bees's Honey Slime mob instead of Vanilla Slime.
		#
		spawnHoneySlimeMob = true
		# 
		#-----------------------------------------------------
		#
		# Place Buzzier Bees's Wax Blocks on the surface of land /r/n around sea level and below too.
		#
		waxBlocksWorldgen = true
		# 
		#-----------------------------------------------------
		#
		# Allow Honey Wand to take honey from Filled Porous Honeycomb Block 
		# and put honey into Porous Honeycomb Block without angering bees.
		#
		allowHoneyWandCompat = true

